config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

  resources :lists do 
    resources :ingredients
  end

  resources :ratings
  resources :comments

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :list #recipe list.

  validates :content, presence: true
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_ingredients
  has_many :lists, through: :recipe_ingredients

  validates :description, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :comments
  has_many :ratings
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  validates_presence_of :name

  def ingredients_attributes=(ingredients_attributes)
    ingredients_attributes.values.each do |ingredient|
      
      if !(ingredient["description"] == "")
        self.ingredients << Ingredient.find_or_create_by(description: ingredient)
      end
    end
  end

  def comments_attributes=(comments_attributes)
    comments_attributes.values.each do |comment|

      if !(comment["content"] == "")
        self.comment << Comment.find_or_create_by(content: comment)
      end
    end
  end

  def ratings_attributes=(ratings_attributes)
    ratings_attributes.values.each do |rating|

      if !(rating["star_rating"] == "")
        self.ratings << Rating.find_or_create_by(star_rating: rating)
      end
    end
  end
end 

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user 
  belongs_to :list #recipe list

  validates :star_rating, presence: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :list
  belongs_to :ingredient
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password 
  before_save :social_login?
  has_many :ingredients
  has_many :lists, :through => :ingredients
  has_many :comments
  
  validates_presence_of :name, :email
  validates :email, uniqueness: true

  def social_login?
    
    if uid
      password = "f@c3b00k"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
    helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
  end

  def create
    #binding.pry
    @list = List.find_by(id: comment_params[:list_id])
    @comment = @list.comments.create(comment_params)

    redirect_to lists_path(@list)
  end

  def show
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :user_id, :list_id)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @ingredient = @list.ingredients.build
  end

  def create
    @list = List.find(params[:list_id])
    @ingredient = @list.ingredients.create(ingredient_params)

    redirect_to list_path(@list)
  end

  def show
  end

  def update
    find_ingredients
    @ingredient.update(@ingredient_params)
    @ingredient.save

    redirect_to ingredient_path(@ingredient)
  end

  def edit
    find_ingredients
  end

  def destroy
    find_ingredients
    @ingredient.destroy
    
    redirect_to root_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:description, :list_id)
  end

  def find_ingredients
    @ingredient = Ingredient.find(params[:id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  def index
    #binding.pry
    @lists = List.all
  end

  def show
    find_recipe
    @comment = Comment.new
    @rating = Rating.new
  end

  def new
    @lists = List.all
    @list = List.new
    5.times {@list.ingredients.build}
  end
  
  def create
    @list = List.create(list_params)
    #binding.pry
    # list_params = {id:somethign, name:something, ingredients_attributes:{description:'sauce'}}
    @list.user = current_user
    @list.save

    redirect_to lists_path(@list)
  end

  def update
    find_recipe
    @list.update(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  def edit
    find_recipe
  end

  def destroy
    find_recipe
    @list.destroy
    
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :user_id, :content, ingredients_attributes: :description, comments_attributes: :content, ratings_attributes: :star_rating)
  end

  def find_recipe
    #binding.pry
    @list = List.find(params[:id])
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def new
  end

  def create
    #binding.pry
    @list = List.find_by(id: rating_params[:list_id])
    @rating = @list.ratings.create(rating_params)

    redirect_to lists_path(@list)
  end

  def show
  end

  private

  def rating_params
    params.require(:rating).permit(:star_rating, :list_id, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    
    if auth.nil?
      @user = User.find_by(email: params[:user][:email])
      if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id 
      redirect_to root_path
      else
      @error = "Try Again"
      render :new
      end
   
    else 
      @user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
      end
      
      @user.save
      session[:user_id] = @user.id
      redirect_to root_path

    end
  end 

  def auth
    request.env['omniauth.auth']
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end


  private 
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @lists = List.all
    @user = current_user 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/_form.html.erb
<%= form_for ([list, ingredient]) do |f| %>
  
  <%= f.label 'Ingredient' %>
  <%= f.text_field :description %>
  
<%= f.submit "Add Ingredient" %>
<% end %>

app/views/ingredients/new.html.erb
<%= render partial: 'form', locals: {ingredient: @ingredient, list: @list} %>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %><br>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

 
    <%= f.fields_for :ingredients_attributes do |ingredient| %> 
        <%= ingredient.label 'Ingredients:' %>
        <%= ingredient.text_field :description %>

    <% end %>
  

<%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<%=render partial: 'form', locals: {list: @list}%>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <%= link_to list.name, list_path(list) %><br>
<% end %>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= form_for @rating do |f| %>
   1 <%= f.radio_button :star_rating, "1"%> | 2 <%= f.radio_button :star_rating, "2"%> | 3 <%= f.radio_button :star_rating, "3"%> | 4 <%= f.radio_button :star_rating, "4"%> | 5 <%= f.radio_button :star_rating, "5"%> |
  <%= f.hidden_field :list_id, value: @list.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add Rating" %>
<%end%>

<h3>Ingredients:</h3>

<ol>
  <% @list.ingredients.each do |ingredient| %>
    <li><%= ingredient.description %></li><br>
  <% end %>
</ol>

<%= button_to "Add Ingredients", new_list_ingredient_path(@list), method: 'get' %>
<%= button_to "Edit Recipe", edit_list_path(@list), method: 'get' %>
<%= button_to "Delete Recipe", "/lists/#{@list.id}", method: 'delete' %><br>

<%= form_for @comment do |f| %>
  <%= f.text_field :content, placeholder: "New comment" %>
  <%= f.hidden_field :list_id, value: @list.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add Comment" %>
<% end %>

<% @list.comments.each do |comment| %>
  <p><%= comment.content %></p>
<% end %>

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_overview">
    <h2>There were errors:</h2>
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(:user, action: 'signup') do |f| %>
  <% if user.errors[:name].empty? %>
    <div class="field">
  <% else %>
    <div class="field_with_errors">
  <% end %>
      <%= f.label :name %>
      <%= f.text_field :name%><br>
    </div>

  <% if user.errors[:email].empty? %>
    <div class="field">
  <% else %>
    <div class="field_with_errors">
  <% end %>
      <%= f.label :email %>
      <%= f.text_field :email %><br>
    </div>

  <% if user.errors[:password].empty? %>
    <div class="field">
  <% else %>
    <div class="field_with_errors">
  <% end %>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
      <%= f.submit "Sign Up" %>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=render partial: 'form', locals: {user: @user}%>
<%= link_to("Login with Facebook!", "/auth/facebook") %>

app/views/welcome/home.html.erb
<div class="container">
  <div class="jumbotron">
    <% if !session[:user_id] %>
      <%=render partial: 'sessions/form', locals: {user: @user}%>
      <%= link_to("Login with Facebook!", "/auth/facebook") %>
    <% else %>
      <h5>Welcome, <%= @user.name if @user.name %></h5>
      <h2>Recipe Site</h2>

      <p>This website allows you to create your recipe along with its ingredients. Have fun creating great foods to eat.</p>

      <h3>All Recipes:</h3>

      <% @lists.each do |list| %>
        <h5><%=link_to list.name, list_path(list)%> Rating <% list.ratings.each do |rating| %>
          <%= rating.star_rating %>/5
        <% end %><br></h5>
      <% end %>
      <%= button_to 'Create New Recipe', new_list_path, method: 'get' %>
    <% end %>  
  </div>
</div>

<div class="container">
  <div id="footer">
    <div class="container">
      <p class="text-info">By - <a href="https://github.com/pacosta613" target="_blank">Pedro J. Acosta</a></p>
    </div>
  </div>
</div>